export const CITIES_OPTIONS = [
  {label: 'Albury', value: 'Albury'},
  {label: 'Ballina', value: 'Ballina'},
  {label: 'Batemans Bay', value: 'Batemans Bay'},
  {label: 'Bathurst', value: 'Bathurst'},
  {label: 'Bourke', value: 'Bourke'},
  {label: 'Broken Hill', value: 'Broken Hill'},
  {label: 'Byron Bay', value: 'Byron Bay'},
  {label: 'Central Coast', value: 'Central Coast'},
  {label: 'Coffs harbour', value: 'Coffs harbour'},
  {label: 'Dubbo', value: 'Dubbo'},
  {label: 'Gosford', value: 'Gosford'},
  {label: 'Goulburn', value: 'Goulburn'},
  {label: 'Goulburn Valley', value: 'Goulburn Valley'},
  {label: 'Grafton', value: 'Grafton'},
  {label: 'Hunter Valley', value: 'Hunter Valley'},
  {label: 'Lismore', value: 'Lismore'},
  {label: 'Maitland', value: 'Maitland'},
  {label: 'Muswellbrook', value: 'Muswellbrook'},
  {label: 'Newcastle', value: 'Newcastle'},
  {label: 'Nowra', value: 'Nowra'},
  {label: 'Orange', value: 'Orange'},
  {label: 'Port Macquarie', value: 'Port Macquarie'},
  {label: 'Raymond Terrace', value: 'Raymond Terrace'},
  {label: 'Singleton', value: 'Singleton'},
  {label: 'Tamworth', value: 'Tamworth'},
  {label: 'Wagga wagga', value: 'Wagga wagga'},
  {label: 'Wollongong', value: 'Wollongong'},
  {label: 'Sydney', value: 'Sydney'},
  {label: 'Bega', value: 'Bega'},
  {label: 'Port Stephens', value: 'Port Stephens'},
  {label: 'Mudgee', value: 'Mudgee'},
  {label: 'Moama', value: 'Moama'},
  {label: 'Ulladulla', value: 'Ulladulla'},
  {label: 'Tweed Heads', value: 'Tweed Heads'},
  {label: 'Blue Mountains', value: 'Blue Mountains'},
  {label: 'Lake Macquarie', value: 'Lake Macquarie'},
  {label: 'Lennox Head', value: 'Lennox Head'},
  {label: 'Cobar', value: 'Cobar'},
  {label: 'Armidale', value: 'Armidale'},
  {label: 'Lithgow', value: 'Lithgow'},
  {label: 'Griffith', value: 'Griffith'},
  {label: 'Jindabyne', value: 'Jindabyne'},
  {label: 'Thredbo', value: 'Thredbo'},
  {label: 'Deniliquin', value: 'Deniliquin'},
  {label: 'Eden', value: 'Eden'},
  {label: 'Kiama', value: 'Kiama'},
  {label: 'Young', value: 'Young'},
  {label: 'Cootamundra', value: 'Cootamundra'},
  {label: 'Junee', value: 'Junee'},
  {label: 'Cowra', value: 'Cowra'},
  {label: 'Temora', value: 'Temora'},
  {label: 'Parkes', value: 'Parkes'},
  {label: 'Gundagai', value: 'Gundagai'},
  {label: 'Leeton', value: 'Leeton'},
  {label: 'Tumut', value: 'Tumut'},
  {label: 'Narrandera', value: 'Narrandera'},
  {label: 'Tarcutta', value: 'Tarcutta'},
  {label: 'Holbrook', value: 'Holbrook'},
  {label: 'Huskisson', value: 'Huskisson'},
  {label: 'Nambucca Heads', value: 'Nambucca Heads'},
  {label: 'Forbes', value: 'Forbes'},
  {label: 'Jervis Bay', value: 'Jervis Bay'},
  {label: 'Condobolin', value: 'Condobolin'},
  {label: 'Pambula', value: 'Pambula'},
  {label: 'Merimbula', value: 'Merimbula'},
  {label: 'Casino', value: 'Casino'},
  {label: 'Gunnedah', value: 'Gunnedah'},
  {label: 'Inverell', value: 'Inverell'},
  {label: 'Coonabarabran', value: 'Coonabarabran'},
  {label: 'Taree', value: 'Taree'},
  {label: 'West Wyalong', value: 'West Wyalong'},
  {label: 'Bowral', value: 'Bowral'},
  {label: 'Narrabri', value: 'Narrabri'},
  {label: 'Glen Innes', value: 'Glen Innes'},
  {label: 'Bellingen', value: 'Bellingen'},
  {label: 'Jenolan', value: 'Jenolan'},
  {label: 'Ardlethan', value: 'Ardlethan'},
  {label: 'Hay', value: 'Hay'},
  {label: 'Queanbeyan', value: 'Queanbeyan'},
  {label: 'Oberon', value: 'Oberon'},
  {label: 'Narooma', value: 'Narooma'},
  {label: 'Mittagong', value: 'Mittagong'},
  {label: 'Moss Vale', value: 'Moss Vale'},
  {label: 'Yass', value: 'Yass'},
  {label: 'South West Rocks', value: 'South West Rocks'},
  {label: 'Moree', value: 'Moree'},
  {label: 'Anna Bay', value: 'Anna Bay'},
  {label: 'Parramatta', value: 'Parramatta'},
  {label: 'Palm Beach', value: 'Palm Beach'},
  {label: 'Forster', value: 'Forster'},
  {label: 'Tuncurry', value: 'Tuncurry'},
  {label: 'Sydney CBD', value: 'Sydney CBD'},
  {label: 'Cooma', value: ''},
  {label: 'Brisbane', value: 'Brisbane'},
  {label: 'Gold Coast', value: 'Gold Coast'},
  {label: 'Sunshine Coast', value: 'Sunshine Coast'},
  {label: 'Bundaberg', value: 'Bundaberg'},
  {label: 'Cairns', value: 'Cairns'},
  {label: 'Fraser coast', value: 'Fraser coast'},
  {label: 'Gladstone', value: 'Gladstone'},
  {label: 'Gyumpie', value: 'Gyumpie'},
  {label: 'Hervey bay', value: 'Hervey bay'},
  {label: 'Ipswich', value: 'Ipswich'},
  {label: 'Longreach', value: 'Longreach'},
  {label: 'Mackay', value: 'Mackay'},
  {label: 'Maryborough', value: 'Maryborough'},
  {label: 'Mount Isa', value: 'Mount Isa'},
  {label: 'Rockhampton', value: 'Rockhampton'},
  {label: 'Toowoomba', value: 'Toowoomba'},
  {label: 'Townsville', value: 'Townsville'},
  {label: 'Whitsundays', value: 'Whitsundays'},
  {label: 'Port Douglas', value: 'Port Douglas'},
  {label: 'Airlie Beach', value: 'Airlie Beach'},
  {label: 'Weipa', value: 'Weipa'},
  {label: 'Innisfail', value: 'Innisfail'},
  {label: 'Atherton', value: 'Atherton'},
  {label: 'Palm Cove', value: 'Palm Cove'},
  {label: 'Emerald', value: 'Emerald'},
  {label: 'Moranbah', value: 'Moranbah'},
  {label: 'Roma', value: 'Roma'},
  {label: 'Warwick', value: 'Warwick'},
  {label: 'Proserpine', value: 'Proserpine'},
  {label: 'Chinchilla', value: 'Chinchilla'},
  {label: 'Goondiwindi', value: 'Goondiwindi'},
  {label: 'Bribie Island', value: 'Bribie Island'},
  {label: 'Heathcote', value: 'Heathcote'},
  {label: 'Stanwell', value: 'Stanwell'},
  {label: 'Dalby', value: 'Dalby'},
  {label: 'Melbourne', value: 'Melbourne'},
  {label: 'Bainsdale', value: 'Bainsdale'},
  {label: 'Ballarat', value: 'Ballarat'},
  {label: 'Bendigo', value: 'Bendigo'},
  {label: 'Geelong', value: 'Geelong'},
  {label: 'Gippsland', value: 'Gippsland'},
  {label: 'La Trobe valley', value: 'La Trobe valley'},
  {label: 'Melton', value: 'Melton'},
  {label: 'Mildura', value: 'Mildura'},
  {label: 'Moe', value: 'Moe'},
  {label: 'Morwell', value: 'Morwell'},
  {label: 'Pakenham', value: 'Pakenham'},
  {label: 'Sale', value: 'Sale'},
  {label: 'Shepparton', value: 'Shepparton'},
  {label: 'Sunbury', value: 'Sunbury'},
  {label: 'Traralgon', value: 'Traralgon'},
  {label: 'Warragul', value: 'Warragul'},
  {label: 'Warrnambool', value: 'Warrnambool'},
  {label: 'Wodonga', value: 'Wodonga'},
  {label: 'Mornington Peninsula', value: 'Mornington Peninsula'},
  {label: 'Frankston', value: 'Frankston'},
  {label: 'Surf Coast Shire', value: 'Surf Coast Shire'},
  {label: 'Yarrawonga', value: 'Yarrawonga'},
  {label: 'Echuca', value: 'Echuca'},
  {label: 'Swan Hill', value: 'Swan Hill'},
  {label: 'Phillip Island', value: 'Phillip Island'},
  {label: 'Horsham', value: 'Horsham'},
  {label: 'Seymour', value: 'Seymour'},
  {label: 'Kilmore', value: 'Kilmore'},
  {label: 'Wangaratta', value: 'Wangaratta'},
  {label: 'Benalla', value: 'Benalla'},
  {label: 'Stawell', value: 'Stawell'},
  {label: 'Portland', value: 'Portland'},
  {label: 'Drouin', value: 'Drouin'},
  {label: 'Lakes Entrance', value: 'Lakes Entrance'},
  {label: 'Mount Buller', value: 'Mount Buller'},
  {label: 'Mount Hotham', value: 'Mount Hotham'},
  {label: 'Falls Creek', value: 'Falls Creek'},
  {label: 'Beechworth', value: 'Beechworth'},
  {label: 'Colac', value: 'Colac'},
  {label: 'Drysdale', value: 'Drysdale'},
  {label: 'Cowes', value: 'Cowes'},
  {label: 'Bellarine', value: 'Bellarine'},
  {label: 'Healesville', value: 'Healesville'},
  {label: 'Canberra', value: 'Canberra'},
  {label: 'Vic', value: 'Vic'},
  {label: 'Darwin', value: 'Darwin'},
  {label: 'Alice springs', value: 'Alice springs'},
  {label: 'Katherine', value: 'Katherine'},
  {label: 'Tennant Creek', value: 'Tennant Creek'},
  {label: 'Perth', value: 'Perth'},
  {label: 'Albany', value: 'Albany'},
  {label: 'Broome', value: 'Broome'},
  {label: 'Bunbury', value: 'Bunbury'},
  {label: 'Busselton', value: 'Busselton'},
  {label: 'Esperance', value: 'Esperance'},
  {label: 'Geraldton', value: 'Geraldton'},
  {label: 'Kalgoorlie', value: 'Kalgoorlie'},
  {label: 'Karratha', value: 'Karratha'},
  {label: 'Kununurra', value: 'Kununurra'},
  {label: 'Mandurah', value: 'Mandurah'},
  {label: 'Margaret River', value: 'Margaret River'},
  {label: 'Port Hedland', value: 'Port Hedland'},
  {label: 'Dunsborough', value: 'Dunsborough'},
  {label: 'Fremantle', value: 'Fremantle'},
  {label: 'Perth CBD', value: 'Perth CBD'},
  {label: 'Exmouth', value: 'Exmouth'},
  {label: 'Northam', value: 'Northam'},
  {label: 'Lancelin', value: 'Lancelin'},
  {label: 'Pinjarra', value: 'Pinjarra'},
  {label: 'Harvey', value: 'Harvey'},
  {label: 'Jurien Bay', value: 'Jurien Bay'},
  {label: 'Hobart', value: 'Hobart'},
  {label: 'Burnie', value: 'Burnie'},
  {label: 'Devonport', value: 'Devonport'},
  {label: 'Launceston', value: 'Launceston'},
  {label: 'Strahan', value: 'Strahan'},
  {label: 'Adelaide', value: 'Adelaide'},
  {label: 'Adelaide Hills', value: 'Adelaide Hills'},
  {label: 'Barossa Valley', value: 'Barossa Valley'},
  {label: 'Coober Pedy', value: 'Coober Pedy'},
  {label: 'Mount Gambier', value: 'Mount Gambier'},
  {label: 'Port Lincoln', value: 'Port Lincoln'},
  {label: 'Port Augusta', value: 'Port Augusta'},
  {label: 'Whyalla', value: 'Whyalla'},
  {label: 'Port Pirie', value: 'Port Pirie'},
  {label: 'Riverland', value: 'Riverland'},
  {label: 'Gawler', value: 'Gawler'},
  {label: 'Mount Barker', value: 'Mount Barker'},
  {label: 'Murray Bridge', value: 'Murray Bridge'},
  {label: 'Victor Harbour', value: 'Victor Harbour'},
]
