export const SEARCH_AND_FILTER_POPULATE_FIELDS = `fields[0]=name&fields[1]=lastName&fields[2]=username&fields[3]=age&fields[4]=placeOfService&fields[5]=dressSize&fields[6]=hairColor&fields[7]=badge&fields[8]=hairColor&fields[9]=city&fields[10]=gender&populate[services][fields]&populate[incallRates][fields][1]=duration&populate[incallRates][fields][2]=price&populate[incallRates][fields][3]=additionalInfo&populate[outcallRates][fields][1]=duration&populate[outcallRates][fields][2]=price&populate[outcallRates][fields][3]=additionalInfo&populate[profilePicture][fields][1]=url&populate[profilePicture][fields][2]=name&populate[profilePicture][fields][3]=alternativeText&populate[profilePicture][fields][4]=width&populate[profilePicture][fields][5]=height
`;

export const  LOCATION_POPULATE_FIELDS = `populate[image_banner_landscape_for_desktop][fields]
[0]=height&populate[image_banner_landscape_for_desktop][fields]
[1]=url&populate[image_banner_landscape_for_desktop][fields]
[2]=name&populate[image_banner_landscape_for_desktop][fields]
[3]=alternativeText&populate[image_banner_landscape_for_desktop][fields]
[4]=width&populate[image_banner_portrait_for_mobile][fields]
[0]=height&populate[image_banner_portrait_for_mobile][fields]
[1]=url&populate[image_banner_portrait_for_mobile][fields]
[2]=name&populate[image_banner_portrait_for_mobile][fields]
[3]=alternativeText&populate[image_banner_portrait_for_mobile][fields]
[4]=width&populate[providers][fields]
[0]=name&populate[providers][fields]
[1]=lastName&populate[providers][fields]
[2]=username&populate[providers][fields]
[3]=age&populate[providers][fields]
[4]=placeOfService&populate[providers][fields]
[5]=dressSize&&populate[providers][fields]
[6]=hairColor&populate[providers][fields]
[7]=badge&populate[providers][fields]
[8]=hairColor&populate[providers][fields]
[9]=city&populate[providers][fields]
[10]=gender&populate[providers][populate]
[0]=services&populate[providers][populate]
[1]=profilePicture&populate[providers][populate]
[2]=incallRates&populate[providers][populate]
[3]=outcallRates`;

export const  COLLECTION_POPULATE_FIELDS = `populate[providers][fields]
[0]=name&populate[providers][fields]
[1]=lastName&populate[providers][fields]
[2]=username&populate[providers][fields]
[3]=age&populate[providers][fields]
[4]=placeOfService&populate[providers][fields]
[5]=dressSize&&populate[providers][fields]
[6]=hairColor&populate[providers][fields]
[7]=badge&populate[providers][fields]
[8]=hairColor&populate[providers][fields]
[9]=city&populate[providers][fields]
[10]=gender&populate[providers][populate]
[0]=services&populate[providers][populate]
[1]=profilePicture&populate[providers][populate]
[2]=incallRates&populate[providers][populate]
[3]=outcallRates`;
