export const RATES_OPTIONS = [
  {label: '30 minutes', value: '30 minutes'},
  {label: '45 minutes', value: '45 minutes'},
  {label: '1 hour', value: '1 hour'},
  {label: '1.5 hours', value: '1.5 hours'},
  {label: '2 hours', value: '2 hours'},
  {label: '3 hours', value: '3 hours'},
  {label: '4 hours', value: '4 hours'},
  {label: '5 hours', value: '5 hours'},
  {label: '6 hours', value: '6 hours'},
  {label: '7 hours', value: '7 hours'},
  {label: '8 hours', value: '8 hours'},
  {label: '9 hours', value: '9 hours'},
  {label: '10 hours', value: '10 hours'},
  {label: '12 hours', value: '12 hours'},
  {label: '15 hours', value: '15 hours'},
  {label: '18 hours', value: '18 hours'},
  {label: '24 hours', value: '24 hours'},
  {label: '36 hours', value: '36 hours'},
  {label: '48 hours', value: '48 hours'},
  {label: 'Additional hours', value: 'Additional hours'},
  {label: 'Overnight', value: 'Overnight'},
  {label: 'Dinner Date', value: 'Dinner Date'},
  {label: 'Couples', value: 'Couples'},
  {label: 'Weekend', value: 'Weekend'},
  {label: 'Duos with another escort', value: 'Duos with another escort'},
  {label: 'Social date', value: 'Social date'},
]
