export const AGE_OPTIONS = [
  { value: '18', label: '18' },
  { value: '19', label: '19' },
  { value: '20', label: '20' },
  { value: '21', label: '21' },
  { value: '22', label: '22' },
  { value: '23', label: '23' },
  { value: '24', label: '24' },
  { value: '25', label: '25' },
  { value: '26', label: '26' },
  { value: '27', label: '27' },
  { value: '28', label: '28' },
  { value: '29', label: '29' },
  { value: '30', label: '30' },
  { value: '31', label: '31' },
  { value: '32', label: '32' },
  { value: '33', label: '33' },
  { value: '34', label: '34' },
  { value: '35', label: '35' },
  { value: '36', label: '36' },
  { value: '37', label: '37' },
  { value: '38', label: '38' },
  { value: '39', label: '39' },
  { value: '40', label: '40' },
  { value: '41', label: '41' },
  { value: '42', label: '42' },
  { value: '43', label: '43' },
  { value: '44', label: '44' },
  { value: '45', label: '45' },
  { value: '46', label: '46' },
  { value: '47', label: '47' },
  { value: '48', label: '48' },
  { value: '49', label: '49' },
  { value: '50', label: '50' },
  { value: '51', label: '51' },
  { value: '52', label: '52' },
  { value: '53', label: '53' },
  { value: '54', label: '54' },
  { value: '55', label: '55' },
  { value: '56', label: '56' },
  { value: '57', label: '57' },
  { value: '58', label: '58' },
  { value: '59', label: '59' },
  { value: '50', label: '50' },
  { value: '61', label: '61' },
  { value: '62', label: '62' },
  { value: '63', label: '63' },
  { value: '64', label: '64' },
  { value: '65', label: '65' },
  { value: '66', label: '66' },
  { value: '67', label: '67' },
  { value: '68', label: '68' },
  { value: '69', label: '69' },
  { value: '70', label: '70' },
  { value: `20's`, label: `20's` },
  { value: `30's`, label: `30's` },
  { value: `40's`, label: `40's` },
  { value: `50's`, label: `50's` },
  { value: 'cougar', label: 'cougar' },
  { value: 'MILF', label: 'MILF' },
];

export const EYE_COLOR_OPTIONS = [
  {value: 'Grey', label: 'Grey'},
  {value: 'Hazel', label: 'Hazel'},
  {value: 'Green', label: 'Green'},
  {value: 'Blue', label: 'Blue'},
  {value: 'Black', label: 'Black'},
  {value: 'Brown', label: 'Brown'},
];

export const HAIR_COLOR_OPTIONS = [
  {value: 'black', label: 'Black'},
  {value: 'blonde', label: 'Blonde'},
  {value: 'red', label: 'Red'},
  {value: 'brunette', label: 'Brunette'},
  {value: 'caramel', label: 'Caramel'},
  {value: 'auburn', label: 'Auburn'},
  {value: 'platinum blonde', label: 'Platinum blonde'},
  {value: 'strawberry blonde', label: 'Strawberry blonde'},
  {value: 'pink', label: 'Pink'},
  {value: 'blue', label: 'Blue'},
  {value: 'purple', label: 'Purple'},
  {value: 'green', label: 'Green'},
]

export const HEIGHT_OPTIONS = [
  {value: '150 cm', label: '150 cm'},
  {value: '151 cm', label: '151 cm'},
  {value: '152 cm', label: '152 cm'},
  {value: '153 cm', label: '153 cm'},
  {value: '154 cm', label: '154 cm'},
  {value: '155 cm', label: '155 cm'},
  {value: '156 cm', label: '156 cm'},
  {value: '157 cm', label: '157 cm'},
  {value: '158 cm', label: '158 cm'},
  {value: '159 cm', label: '159 cm'},
  {value: '160 cm', label: '160 cm'},
  {value: '161 cm', label: '161 cm'},
  {value: '162 cm', label: '162 cm'},
  {value: '163 cm', label: '163 cm'},
  {value: '164 cm', label: '164 cm'},
  {value: '165 cm', label: '165 cm'},
  {value: '166 cm', label: '166 cm'},
  {value: '167 cm', label: '167 cm'},
  {value: '168 cm', label: '168 cm'},
  {value: '169 cm', label: '169 cm'},
  {value: '170 cm', label: '170 cm'},
  {value: '171 cm', label: '171 cm'},
  {value: '172 cm', label: '172 cm'},
  {value: '173 cm', label: '173 cm'},
  {value: '174 cm', label: '174 cm'},
  {value: '175 cm', label: '175 cm'},
  {value: '176 cm', label: '176 cm'},
  {value: '177 cm', label: '177 cm'},
  {value: '178 cm', label: '178 cm'},
  {value: '179 cm', label: '179 cm'},
  {value: '180 cm', label: '180 cm'},
  {value: '181 cm', label: '181 cm'},
  {value: '182 cm', label: '182 cm'},
  {value: '183 cm', label: '183 cm'},
  {value: '184 cm', label: '184 cm'},
  {value: '185 cm', label: '185 cm'},
  {value: '186 cm', label: '186 cm'},
  {value: '187 cm', label: '187 cm'},
  {value: '188 cm', label: '188 cm'},
  {value: '189 cm', label: '189 cm'},
  {value: '190 cm', label: '190 cm'},
  {value: '191 cm', label: '191 cm'},
  {value: '192 cm', label: '192 cm'},
  {value: '193 cm', label: '193 cm'},
  {value: '194 cm', label: '194 cm'},
  {value: '195 cm', label: '195 cm'},
  {value: '196 cm', label: '196 cm'},
  {value: '197 cm', label: '197 cm'},
  {value: '198 cm', label: '198 cm'},
  {value: '199 cm', label: '199 cm'},
  {value: '200 cm', label: '200 cm'},
  {value: '201 cm', label: '201 cm'},
  {value: '202 cm', label: '202 cm'},
  {value: '203 cm', label: '203 cm'},
  {value: '204 cm', label: '204 cm'},
  {value: '205 cm', label: '205 cm'},
  {value: '206 cm', label: '206 cm'},
  {value: '207 cm', label: '207 cm'},
  {value: '208 cm', label: '208 cm'},
  {value: '209 cm', label: '209 cm'},
  {value: '210 cm', label: '210 cm'},
]

export const PLACE_OF_SERVICE_OPTIONS = [
  {value: 'In-Call', label: 'In-Call'},
  {value: 'Out-Call', label: 'Out-Call'},
  {value: 'In-Call, Out-Call', label: 'In-Call, Out-Call'},
]

export const BUST_OPTIONS = [
  {value: 'A Cup', label: 'A Cup'},
  {value: 'B Cup', label: 'B Cup'},
  {value: 'C Cup', label: 'C Cup'},
  {value: 'D Cup', label: 'D Cup'},
  {value: 'DD Cup', label: 'DD Cup'},
  {value: 'E Cup', label: 'E Cup'},
  {value: 'F Cup', label: 'F Cup'},
  {value: 'H Cup', label: 'H Cup'},
  {value: 'I Cup', label: 'I Cup'},
  {value: 'J Cup', label: 'J Cup'},
  {value: 'K Cup', label: 'K Cup'},
]

export const BODY_TYPE_OPTIONS = [
  {value: 'curvy', label: 'Curvy'},
  {value: 'athletic', label: 'Athletic'},
  {value: 'slim', label: 'Slim'},
  {value: 'voluptuous', label: 'Voluptuous'},
  {value: 'busty', label: 'Busty'},
  {value: 'bbw', label: 'Bbw'},
  {value: 'hour glass', label: 'Hour glass'},
  {value: 'petite', label: 'Petite'},
  {value: 'toned', label: 'Toned'},
]

export const GENDER_OPTIONS = [
  {value: 'male', label: 'Male'},
  {value: 'female', label: 'Female'},
  {value: 'trans', label: 'Trans'},
]

export const DIGITAL_SERVICE_OPTIONS = [
  {value: true, label: 'Yes'},
  {value: false, label: 'No'},
]
