export const WISHLIST_OPTIONS = [
  { value: 'wine', label: 'Wine' },
  { value: 'vouchers', label: 'Vouchers' },
  { value: 'toys', label: 'Toys' },
  { value: 'spa / massage', label: 'Spa / massage' },
  { value: 'skin care', label: 'Skin care' },
  { value: 'shoes', label: 'Shoes' },
  { value: 'perfume', label: 'Perfume' },
  { value: 'music', label: 'Music' },
  { value: 'lingerie', label: 'Lingerie' },
  { value: 'jewellery', label: 'Jewellery' },
  { value: 'handbags', label: 'handbags' },
  { value: 'gift cards', label: 'Gift cards' },
  { value: 'food', label: 'Food' },
  { value: 'flowers', label: 'Flowers' },
  { value: 'costumes', label: 'Costumes' },
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'books', label: 'Books' },
  { value: 'art', label: 'Art' },
]
