export const USER_FORM = (user) => {
  return {
    email: user.email,
    username: user.username,
    gender: '',
    name: '',
    lastName: '',
    country: '',
    city: '',
    suburbs: [],
    age: '',
    eyeColor: '',
    height: '',
    bust: '',
    dressSize: '',
    hairColor: '',
    bodyType: '',
    placeOfService: '',
    photos: [],
    selfies: [],
    coverPhoto: '',
    profilePicture: '',
    phoneNumber: '',
    contactInfo: '',
    instagramLink: '',
    onlyFansLink: '',
    websiteLink: '',
    aboutMe: '',
    outfits: [],
    makeup: [],
    costume: [],
    extras: [],
    incallRates: [],
    outcallRates: [],
    services: [],
    schedule: [
      { workday: 'Monday', start: '', end: '' },
      { workday: 'Tuesday', start: '', end: '' },
      { workday: 'Wednesday', start: '', end: '' },
      { workday: 'Thursday', start: '', end: '' },
      { workday: 'Friday', start: '', end: '' },
      { workday: 'Saturday', start: '', end: '' },
      { workday: 'Sunday', start: '', end: '' }
    ],
    additionalInfo: [],
    reviews: [],
    isApprovedByAdmin: false,
  };
} 

export const USER_FORM_WITH_DATA = (user) => {
  return {
    email: user.email,
    username: user.username,
    gender: user.gender,
    name: user.name,
    lastName: user.lastName,
    country: user.country,
    city: user.city,
    suburbs: user.suburbs,
    age: user.age,
    eyeColor: user.eyeColor,
    height: user.height,
    bust: user.bust,
    dressSize: user.dressSize,
    hairColor: user.hairColor,
    bodyType: user.bodyType,
    placeOfService: user.placeOfService,
    photos: user.photos,
    selfies: user.selfies,
    profilePicture: user.profilePicture,
    coverPhoto: user.coverPhoto,
    phoneNumber: user.phoneNumber,
    contactInfo: user.contactInfo,
    instagramLink: user.instagramLink,
    onlyFansLink: user.onlyFansLink,
    websiteLink: user.websiteLink,
    aboutMe: user.aboutMe,
    outfits: user.outfits,
    makeup: user.makeup,
    costume: user.costume,
    extras: user.extras,
    incallRates: user.incallRates,
    outcallRates: user.outcallRates,
    services: user.services,
    schedule: user.schedule.length > 0 ? user.schedule : [
      { workday: 'Monday', start: '', end: '' },
      { workday: 'Tuesday', start: '', end: '' },
      { workday: 'Wednesday', start: '', end: '' },
      { workday: 'Thursday', start: '', end: '' },
      { workday: 'Friday', start: '', end: '' },
      { workday: 'Saturday', start: '', end: '' },
      { workday: 'Sunday', start: '', end: '' }
    ],
    additionalInfo: user.additionalInfo,
    reviews: user.reviews,
    isApprovedByAdmin: user.isApprovedByAdmin,
    favoriteProvidersIds: user.favoriteProvidersIds,
  }
}

export const USER_FORM_NEW_MEMBER = (email, id) => {
  return {
    email: email,
    managerID: id,
    isApprovedByAdmin: false,
    role: 8,
    username: '',
    name: '',
    lastName: '',
    country: '',
    city: '',
    suburbs: [],
    age: '',
    eyeColor: '',
    height: '',
    bust: '',
    dressSize: '',
    hairColor: '',
    bodyType: '',
    placeOfService: '',
    photos: [],
    selfies: [],
    profilePicture: '',
    coverPhoto: '',
    phoneNumber: '',
    contactInfo: '',
    instagramLink: '',
    onlyFansLink: '',
    websiteLink: '',
    aboutMe: '',
    outfits: [],
    makeup: [],
    costume: [],
    extras: [],
    incallRates: [],
    outcallRates: [],
    services: [],
    schedule: [
      { workday: 'Monday', start: '', end: '' },
      { workday: 'Tuesday', start: '', end: '' },
      { workday: 'Wednesday', start: '', end: '' },
      { workday: 'Thursday', start: '', end: '' },
      { workday: 'Friday', start: '', end: '' },
      { workday: 'Saturday', start: '', end: '' },
      { workday: 'Sunday', start: '', end: '' }
    ],
    additionalInfo: [],
    reviews: [],
    favoriteProvidersIds: [],
  }
}

export const USER_REQUIRED_FIELDS = [
  'email',
  'name',
  'lastName',
  'country',
  'city',
  'age',
  'eyeColor',
  'height',
  'placeOfService',
  'photos',
  'coverPhoto',
  'profilePicture',
  'phoneNumber',
  'incallRates',
  'outcallRates',
  'services',
  'schedule',
];

export const USER_REQUIRED_FIELDS_FOR_CLIENT_ROLE = [
  'email',
  'name',
  'lastName',
  'gender',
  'profilePicture',
]

export const USER_REQUIRED_FIELDS_FOR_ADDING_REVIEW = [
  'author',
  'text',
  'date',
]
