export const SERVICES_OPTIONS = [
  // General Services
  { value: 'Core Mathematics', label: 'Core Mathematics (Elementary, Middle, High School)' },
  { value: 'English Language Arts', label: 'English Language Arts (Reading, Writing, Literature)' },
  { value: 'General Science', label: 'General Science (Biology, Chemistry, Physics)' },
  { value: 'History', label: 'History' },
  { value: 'Social Studies', label: 'Social Studies' },
  { value: 'Study Skills', label: 'Study Skills (Time Management, Organization, Note-Taking)' },
  { value: 'Writing and Communication', label: 'Writing and Communication (Essay Writing, Public Speaking)' },
  { value: 'Homework Help', label: 'Homework Help' },
  { value: 'Exam Preparation', label: 'Exam Preparation' },
  { value: 'Academic Coaching', label: 'Academic Coaching' },
  { value: 'Homeschool Support', label: 'Homeschool Support' },
  { value: 'Language Conversation Practice', label: 'Language Conversation Practice' },
  { value: 'Adult Education', label: 'Adult Education' },
  // Specialized Services
  { value: 'Calculus', label: 'Calculus' },
  { value: 'Algebra', label: 'Algebra (Specify Levels)' },
  { value: 'Geometry', label: 'Geometry' },
  { value: 'Statistics', label: 'Statistics' },
  { value: 'Computer Science', label: 'Computer Science (Programming Languages)' },
  { value: 'Foreign Languages', label: 'Foreign Languages (Specify Languages)' },
  { value: 'SAT/ACT Prep', label: 'SAT/ACT Preparation' },
  { value: 'GRE Prep', label: 'GRE Preparation' },
  { value: 'AP Courses', label: 'AP Courses (Specify Courses)' },
  { value: 'IB Courses', label: 'IB Courses (Specify Courses)' },
  { value: 'Music Lessons', label: 'Music Lessons (Specify Instrument/Vocal)' },
  { value: 'Art Lessons', label: 'Art Lessons (Specify Medium)' },
  { value: 'Coding Lessons', label: 'Coding Lessons (Specify Languages)' },
  { value: 'Career Coaching', label: 'Career Coaching' },
  { value: 'Project Assistance', label: 'Project Assistance' },
  { value: 'Test-Taking Strategies', label: 'Test-Taking Strategies' },
  { value: 'Research Skills', label: 'Research Skills' },
  { value: 'Presentation Skills', label: 'Presentation Skills' },
  { value: 'Creative Writing', label: 'Creative Writing' },
  { value: 'Other', label: 'Other (Specify)' },
  // Experienced Services
  { value: 'Advanced Research Mentoring', label: 'Advanced Research Mentoring' },
  { value: 'Professional Development Workshops', label: 'Professional Development Workshops' },
  { value: 'Curriculum Development', label: 'Curriculum Development' },
  { value: 'Higher Education Consulting', label: 'Higher Education Consulting' },
  { value: 'Expert Witness Tutoring', label: 'Expert Witness Tutoring' },
  { value: 'Industry Specific Training', label: 'Industry Specific Training' },
  { value: 'Other', label: 'Other (Specify)' },
];
