export const QUALIFICATIONS_OPTIONS = [
  { value: 'High School Diploma', label: 'High School Diploma' },
  { value: 'Associate\'s Degree', label: 'Associate\'s Degree' },
  { value: 'Bachelor\'s Degree', label: 'Bachelor\'s Degree (Specify Major)' },
  { value: 'Master\'s Degree', label: 'Master\'s Degree (Specify Major)' },
  { value: 'Doctorate (PhD)', label: 'Doctorate (PhD) (Specify Field)' },
  { value: 'Teaching Certification', label: 'Teaching Certification (Specify)' },
  { value: 'Subject Matter Expert Certification', label: 'Subject Matter Expert Certification (Specify)' },
  { value: 'Professional Certification', label: 'Professional Certification (Specify)' },
  { value: 'Industry Specific Certification', label: 'Industry Specific Certification (Specify)' },
  { value: 'Language Proficiency Certification', label: 'Language Proficiency Certification (Specify)' },
  { value: 'Published Author', label: 'Published Author (Specify Field)' },
  { value: 'Research Publications', label: 'Research Publications' },
  { value: 'Awards and Recognition', label: 'Awards and Recognition (Specify)' },
  { value: 'Relevant Coursework', label: 'Relevant Coursework (Specify)' },
  { value: 'Volunteer Experience', label: 'Volunteer Experience (Specify)' },
  { value: 'No Formal Qualifications', label: 'No Formal Qualifications' },
];

export const EXPERIENCE_OPTIONS = [
  { value: 'Less than 1 year', label: 'Less than 1 year' },
  { value: '1-3 years', label: '1-3 years' },
  { value: '3-5 years', label: '3-5 years' },
  { value: '5-10 years', label: '5-10 years' },
  { value: '10+ years', label: '10+ years' },
  { value: 'Specific Industry Experience', label: 'Specific Industry Experience (Specify)' },
  { value: 'Research Experience', label: 'Research Experience' },
  { value: 'Professional Experience', label: 'Professional Experience' },
  { value: 'Teaching Experience', label: 'Teaching Experience' },
  { value: 'Tutoring Experience', label: 'Tutoring Experience' },
  { value: 'Mentoring Experience', label: 'Mentoring Experience' },
  { value: 'Curriculum Development Experience', label: 'Curriculum Development Experience' },
  { value: 'Public Speaking Experience', label: 'Public Speaking Experience' },
  { value: 'Online Tutoring Experience', label: 'Online Tutoring Experience' },
  { value: 'Homeschooling Experience', label: 'Homeschooling Experience' },
];
