export const SERVICES_OPTIONS = [
  { value: 'Affectionate cuddling', label: 'Affectionate cuddling'},
  { value: 'Affectionate kissing', label: 'Affectionate kissing'},
  { value: 'Anal play', label: 'Anal play'},
  { value: 'Anal play - On me', label: 'Anal play - On me'},
  { value: 'Anal play - On you', label: 'Anal play - On you'},
  { value: 'ATM - Ass to mouth', label: 'ATM - Ass to mouth'},
  { value: 'BBBJ - bare black', label: 'BBBJ - bare black'},
  { value: 'B and D - bondage and discipline', label: 'B and D - bondage and discipline'},
  { value: 'BDSM', label: 'BDSM'},
  { value: 'BJ - blow job', label: 'BJ - blow job'},
  { value: 'BS - body slide', label: 'BS - body slide'},
  { value: 'Bi twin (double)', label: 'Bi twin (double)'},
  { value: 'BLS - balls licking and sucking', label: 'BLS - balls licking and sucking'},
  { value: 'Body worship', label: 'Body worship'},
  { value: 'Bondage', label: 'Bondage'},
  { value: 'Brazilian', label: 'Brazilian'},
  { value: 'CBJ - covered blow job', label: 'CBJ - covered blow job'},
  { value: 'CBT - cock and ball torture', label: 'CBT - cock and ball torture'},
  { value: 'CD - cross dressing', label: 'CD - cross dressing'},
  { value: 'CIM - cum in mouth', label: 'CIM - cum in mouth'},
  { value: 'CIMWS - cum in mouth with swallow', label: 'CIMWS - cum in mouth with swallow'},
  { value: 'COB - cum on body', label: 'COB - cum on body'},
  { value: 'COF - cum on face', label: 'COF - cum on face'},
  { value: 'Cougar', label: 'Cougar'},
  { value: 'Costumes', label: 'Costumes'},
  { value: 'Costumes and role play', label: 'Costumes and role play'},
  { value: 'DATY - oral on me', label: 'DATY - oral on me'},
  { value: 'DDP - double digit penetration', label: 'DDP - double digit penetration'},
  { value: 'DFK - deep French kissing', label: 'DFK - deep French kissing'},
  { value: 'Disabled Clients', label: 'Disabled Clients'},
  { value: 'DT - deep throat', label: 'DT - deep throat'},
  { value: 'Dinner companion', label: 'Dinner companion'},
  { value: 'Dirty talk', label: 'Dirty talk'},
  { value: 'Doggy style', label: 'Doggy style'},
  { value: 'DP - double penetration', label: 'DP - double penetration'},
  { value: 'Erotic sensual massage', label: 'Erotic sensual massage'},
  { value: 'FK - French kissing', label: 'FK - French kissing'},
  { value: 'FS - full service', label: 'FS - full service'},
  { value: 'Facial - cum on face', label: 'Facial - cum on face'},
  { value: 'FE - female ejaculation (squirting)', label: 'FE - female ejaculation (squirting)'},
  { value: 'Fetish', label: 'Fetish'},
  { value: 'Filming', label: 'Filming'},
  { value: 'Fire and ice - Hot and cold BJ', label: 'Fire and ice - Hot and cold BJ'},
  { value: 'Fisting', label: 'Fisting'},
  { value: 'Fly Me To You', label: 'Fly Me To You'},
  { value: 'Full oil massage', label: 'Full oil massage'},
  { value: 'Foot fetish', label: 'Foot fetish'},
  { value: 'For Couples', label: 'For Couples'},
  { value: 'GFE - girlfriend experience', label: 'GFE - girlfriend experience'},
  { value: 'GS - golden showers', label: 'GS - golden showers'},
  { value: 'GS - golden shower - On me', label: 'GS - golden shower - On me'},
  { value: 'GS - golden shower - On you', label: 'GS - golden shower - On you'},
  { value: 'Gagging', label: 'Gagging'},
  { value: 'Greek - anal sex', label: 'Greek - anal sex'},
  { value: 'HJ - hand job', label: 'HJ - hand job'},
  { value: 'Happy ending', label: 'Happy ending'},
  { value: 'Italian', label: 'Italian'},
  { value: 'Kissing', label: 'Kissing'},
  { value: 'Lactating (before/after pregnancy)', label: 'Lactating (before/after pregnancy)'},
  { value: 'Light bondage', label: 'Light bondage'},
  { value: 'LK - light kissing', label: 'LK - light kissing'},
  { value: 'Lesbian / Bisexual (Female To Female)', label: 'Lesbian / Bisexual (Female To Female)'},
  { value: 'Light spanking', label: 'Light spanking'},
  { value: 'Massage', label: 'Massage'},
  { value: `MILF - mother I'd like to F`, label: `MILF - mother I'd like to F`},
  { value: 'MMF - male male female', label: 'MMF - male male female'},
  { value: 'MFF - male female female', label: 'MFF - male female female'},
  { value: 'MSOG - multiple shots on goal', label: 'MSOG - multiple shots on goal'},
  { value: 'Maid', label: 'Maid'},
  { value: 'Masturbation', label: 'Masturbation'},
  { value: 'Multiple positions', label: 'Multiple positions'},
  { value: 'Mutual French (oral)', label: 'Mutual French (oral)'},
  { value: 'Mutual masturbation', label: 'Mutual masturbation'},
  { value: 'Mutual natural oral', label: 'Mutual natural oral'},
  { value: 'Natural bash (pubic hair)', label: 'Natural bash (pubic hair)'},
  { value: 'Nurse', label: 'Nurse'},
  { value: 'Nuru', label: 'Nuru'},
  { value: 'Natural oral', label: 'Natural oral'},
  { value: 'Overnight stays', label: 'Overnight stays'},
  { value: 'Pearl Necklace', label: 'Pearl Necklace'},
  { value: 'Photography', label: 'Photography'},
  { value: 'Pregnant', label: 'Pregnant'},
  { value: 'Prostate massage', label: 'Prostate massage'},
  { value: 'PSE - porn star experience', label: 'PSE - porn star experience'},
  { value: 'PSE - porn star experience - With filming', label: 'PSE - porn star experience - With filming'},
  { value: 'Passionate kissing', label: 'Passionate kissing'},
  { value: 'Rimming', label: 'Rimming'},
  { value: 'Rimming - On me', label: 'Rimming - On me'},
  { value: 'Rimming - On you', label: 'Rimming - On you'},
  { value: 'Role play', label: 'Role play'},
  { value: 'Roman Showers (vomit fetish)', label: 'Roman Showers (vomit fetish)'},
  { value: 'School girl', label: 'School girl'},
  { value: 'Secretary', label: 'Secretary'},
  { value: 'Sex toys', label: 'Sex toys'},
  { value: 'Sexy lingerie', label: 'Sexy lingerie'},
  { value: 'Sexy shower for 2', label: 'Sexy shower for 2'},
  { value: 'Social escort', label: 'Social escort'},
  { value: 'Snowballing', label: 'Snowballing'},
  { value: 'Spanish', label: 'Spanish'},
  { value: 'Spanking - On me', label: 'Spanking - On me'},
  { value: 'Spanking - On you', label: 'Spanking - On you'},
  { value: 'Squirting', label: 'Squirting'},
  { value: 'Strap on', label: 'Strap on'},
  { value: 'Strap on - on me', label: 'Strap on - on me'},
  { value: 'Strap on - on you', label: 'Strap on - on you'},
  { value: 'Strip tease', label: 'Strip tease'},
  { value: 'Tantra', label: 'Tantra'},
  { value: 'Tea bagging', label: 'Tea bagging'},
  { value: 'Travel Companion', label: 'Travel Companion'},
  { value: 'Tromboning', label: 'Tromboning'},
  { value: 'BBW - big beautiful woman', label: 'BBW - big beautiful woman'},
  { value: 'Police woman', label: 'Police woman'},
]
