export const USER_FORM = (user) => {
  return {
    email: user.email,
    username: user.username,
    gender: '',
    name: '',
    lastName: '',
    country: '',
    city: '',
    suburbs: [],
    age: '',
    eyeColor: '',
    height: '',
    badge: '',
    hairColor: '',
    placeOfService: '',
    photos: [],
    selfies: [],
    coverPhoto: '',
    profilePicture: '',
    phoneNumber: '',
    contactInfo: '',
    instagramLink: '',
    onlyFansLink: '',
    websiteLink: '',
    aboutMe: '',
    qualifications: [],
    experience: [],
    incall: {
      Specialized: [],
      Experienced: [],
      general: [],
    },
    outcall: {
      Specialized: [],
      Experienced: [],
      general: [],
    },
    services: {
      Specialized: [],
      Experienced: [],
      general: [],
    },
    schedule: [
      { workday: 'Monday', start: '', end: '' },
      { workday: 'Tuesday', start: '', end: '' },
      { workday: 'Wednesday', start: '', end: '' },
      { workday: 'Thursday', start: '', end: '' },
      { workday: 'Friday', start: '', end: '' },
      { workday: 'Saturday', start: '', end: '' },
      { workday: 'Sunday', start: '', end: '' }
    ],
    additionalInfo: [],
    reviews: [],
    isApprovedByAdmin: false,
    verificationStatus: {
      hasBronzeBadge: false,
      hasSilverBadge: false,
      hasGoldBadge: false
    },
    twitterLink: '',
    otherLink: '',
    availableNow: false,
    digitalService: '',
    managerProviderEmail: '',
  };
} 

export const USER_FORM_WITH_DATA = (user) => {
  return {
    email: user.email,
    username: user.username,
    gender: user.gender,
    name: user.name,
    lastName: user.lastName,
    country: user.country,
    city: user.city,
    suburbs: user.suburbs,
    age: user.age,
    eyeColor: user.eyeColor,
    height: user.height,
    badge: user.badge,
    hairColor: user.hairColor,
    placeOfService: user.placeOfService,
    photos: user.photos,
    selfies: user.selfies,
    profilePicture: user.profilePicture,
    coverPhoto: user.coverPhoto,
    phoneNumber: user.phoneNumber,
    contactInfo: user.contactInfo,
    instagramLink: user.instagramLink,
    onlyFansLink: user.onlyFansLink,
    websiteLink: user.websiteLink,
    aboutMe: user.aboutMe,
    qualifications: user.qualifications,
    experience: user.experience,
    incall: user.incall,
    outcall: user.outcall,
    services: user.services,
    schedule: user?.schedule?.length > 0 ? user.schedule : [
      { workday: 'Monday', start: '', end: '' },
      { workday: 'Tuesday', start: '', end: '' },
      { workday: 'Wednesday', start: '', end: '' },
      { workday: 'Thursday', start: '', end: '' },
      { workday: 'Friday', start: '', end: '' },
      { workday: 'Saturday', start: '', end: '' },
      { workday: 'Sunday', start: '', end: '' }
    ],
    additionalInfo: user.additionalInfo,
    reviews: user.reviews,
    isApprovedByAdmin: user.isApprovedByAdmin,
    favoriteProvidersIds: user.favoriteProvidersIds,
    twitterLink: user.twitterLink,
    otherLink: user.otherLink,
    availableNow: user.availableNow,
    digitalService: user.digitalService,
    managerProviderEmail: user.managerProviderEmail,
  }
}

export const USER_FORM_NEW_MEMBER = (email, managerID) => {
  return {
    email: email,
    managerID: managerID,
    isApprovedByAdmin: false,
    role: 12,
    username: '',
    name: '',
    lastName: '',
    country: '',
    city: '',
    suburbs: [],
    age: '',
    eyeColor: '',
    height: '',
    hairColor: '',
    placeOfService: '',
    photos: [],
    selfies: [],
    profilePicture: null,
    coverPhoto: null,
    phoneNumber: '',
    contactInfo: '',
    instagramLink: '',
    onlyFansLink: '',
    websiteLink: '',
    aboutMe: '',
    qualifications: [],
    experience: [],
    incall: {
      Specialized: [],
      Experienced: [],
      general: [],
    },
    outcall: {
      Specialized: [],
      Experienced: [],
      general: [],
    },
    services: {
      Specialized: [],
      Experienced: [],
      general: [],
    },
    schedule: [
      { workday: 'Monday', start: '', end: '' },
      { workday: 'Tuesday', start: '', end: '' },
      { workday: 'Wednesday', start: '', end: '' },
      { workday: 'Thursday', start: '', end: '' },
      { workday: 'Friday', start: '', end: '' },
      { workday: 'Saturday', start: '', end: '' },
      { workday: 'Sunday', start: '', end: '' }
    ],
    additionalInfo: [],
    reviews: [],
    favoriteProvidersIds: [],
    gender: '',
    badge: '',
    twitterLink: '',
    otherLink: '',
    availableNow: false,
    digitalService: '',
    managerProviderEmail: '',
    verificationStatus: {
      hasBronzeBadge: false,
      hasSilverBadge: false,
      hasGoldBadge: false
    },
  }
}

export const USER_REQUIRED_FIELDS = [
  'name',
  'lastName',
  'country',
  'city',
  'age',
  'eyeColor',
  'height',
  'hairColor',
  'placeOfService',
  'photos',
  'coverPhoto',
  'profilePicture',
  'phoneNumber',
  'gender',
  'services',
  'schedule',
];

export const USER_REQUIRED_FIELDS_FOR_CLIENT_ROLE = [
  'profilePicture',
  'name',
  'lastName',
  'gender',
];

export const USER_REQUIRED_FIELDS_FOR_ADDING_REVIEW = [
  'author',
  'text',
  'date',
];

export const USER_FIELDS_IN_PROFILE_EDIT_FORM = [
  'name',
  'lastName',
  'gender',
  'country',
  'city',
  'age',
  'eyeColor',
  'hairColor',
  'placeOfService',
  'height',
  'managerProviderEmail',
  'phoneNumber',
];
